export const ADD_ARTICLE = "ADD_ARTICLE";
export const SWAP_CARD_BACK = "SWAP_CARD_BACK";
export const SWAP_CARD_FRONT = "SWAP_CARD_FRONT";
export const UPDATE_CARD_NUMBER = "UPDATE_CARD_NUMBER";
export const UPDATE_CARD_NAME = "UPDATE_CARD_NAME";
export const UPDATE_CARD_DATE = "UPDATE_CARD_DATE";
export const UPDATE_CARD_SECURITY_CODE = "UPDATE_CARD_SECURITY_CODE";
export const CHANGE_STATE = "CHANEG_STATE";
export const SUBMIT_DETAILS = "SUBMIT_DETAILS";
export const LOADING_PAGE_STATE = "LOADING_PAGE_STATE";

export const MAX_LENGTH = 19;
